include:
  - ../compose.db.yaml

services:
  fast-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fast-api
    env_file:
      - ../.envrc
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ./src:/usr/src/app
      - ./Makefile:/usr/src/app/Makefile
    ports:
      - "3000:3000"
    command: "make start"
    networks:
      - web-framework-n-knocks
    depends_on:
      - db # ROOTのyamlに記載
