include:
  - ../compose.db.yaml

services:
  node-js:
    image: node:latest
    container_name: node-js-naitive
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    command: npm run dev
    networks:
      - web-framework-n-knocks
    depends_on:
      - db # ROOTのyamlに記載
